name: Scrape Internships
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:         # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo requests beautifulsoup4 python-dotenv discord discord.py
          
      - name: Run scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python scraper.py
